[project]
name = "sim-test-pro"
version = "0.1.0"
description = "A report generator to prove your simulator is up to standards."
readme = "README.md"
requires-python = ">=3.13"
license = "GNU GPLv3"
authors = [{ name = "Fabian INGREMEAU" }]
maintainers = [{ name = "Fabian INGREMEAU" }]
keywords = ["simulation", "testing"]
dependencies = ["simconnect (>=0.4.26,<0.5.0)", "matplotlib (>=3.10.1,<4.0.0)"]

[project.urls]
homepage = "https://github.com/Tractorou24/SimTestPro"
repository = "https://github.com/Tractorou24/SimTestPro"
"Bug Tracker" = "https://github.com/Tractorou24/SimTestPro/issues"

# Optional project components
[project.optional-dependencies]
dev = ["ruff"]

# Tooling
[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = ["ALL"]
exclude = ["D211", "D213"]
